{
 "title": "Metrics",
 "description": "HTTP and JMX Metrics. Created by codeguru for Udemy course.",
 "tags": [ "metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "exported_job",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_sum,exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\", http_response_status_code=\"200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\", http_response_status_code!~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=\"200\"}[$__range]))/sum(increase(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\"}[$__range]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\",http_response_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50/P90/P99 Request Duration Trend",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_server_request_duration_seconds_bucket{exported_job=\"${exported_job}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(http_server_request_duration_seconds_bucket{exported_job=\"${exported_job}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_request_duration_seconds_bucket{exported_job=\"${exported_job}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_server_request_duration_seconds_sum{exported_job=\"${exported_job}\"}[$__range])\n)\n/\nsum(\n  rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JMX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_cpu_recent_utilization_ratio{exported_job=\"${exported_job}\"}",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (jvm_memory_type) (\n  avg_over_time(jvm_memory_used_bytes{exported_job=\"${exported_job}\"}[$__range])\n)\n/\nsum by (jvm_memory_type) (\n  avg_over_time(jvm_memory_limit_bytes{exported_job=\"${exported_job}\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread State Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (jvm_thread_state) (\n  jvm_thread_count{exported_job=\"${exported_job}\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Class Loaded/Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 39 },
     "targets": [
      {
       "expr": "jvm_class_loaded_total{exported_job=\"${exported_job}\"}",
       "legendFormat": "Class Loaded"
      },
      {
       "expr": "jvm_class_unloaded_total{exported_job=\"${exported_job}\"}",
       "legendFormat": "Class Unloaded"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (jvm_gc_name) (\n  rate(jvm_gc_duration_seconds_sum{exported_job=\"${exported_job}\"}[$__range])\n)\n/\nsum by (jvm_gc_name) (\n  rate(jvm_gc_duration_seconds_count{exported_job=\"${exported_job}\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}